# Generated by scripts/build.mjs — do not edit, change palette/*.json instead
# Source from bash/zsh. Appends the Lava colors to FZF_DEFAULT_OPTS (idempotent).
LAVA_FZF_COLORS='--color=fg:#cfc6be,bg:-1,hl:#e86b3f,fg+:#f5efe8,bg+:#3a2016,hl+:#e86b3f,info:#8a8079,prompt:#e86b3f,pointer:#e86b3f,marker:#e0aa50,spinner:#e0aa50,header:#74bbac,border:#3a302a,label:#cfc6be,query:#f5efe8,gutter:-1,separator:#3a302a,scrollbar:#61564f'
case " $FZF_DEFAULT_OPTS " in
  *" $LAVA_FZF_COLORS "*) ;;
  *) export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }$LAVA_FZF_COLORS" ;;
esac
