# Generated by scripts/build.mjs — do not edit, change palette/*.json instead
# Source from bash/zsh. Appends the Lava colors to FZF_DEFAULT_OPTS (idempotent).
LAVA_FZF_COLORS='--color=fg:#56514b,bg:-1,hl:#b74727,fg+:#34312f,bg+:#e3e8ed,hl+:#b74727,info:#736d65,prompt:#b74727,pointer:#b74727,marker:#d8a146,spinner:#d8a146,header:#246e61,border:#c9c4ba,label:#56514b,query:#34312f,gutter:-1,separator:#c9c4ba,scrollbar:#8c857b'
case " $FZF_DEFAULT_OPTS " in
  *" $LAVA_FZF_COLORS "*) ;;
  *) export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }$LAVA_FZF_COLORS" ;;
esac
