# Generated by scripts/build.mjs — do not edit, change palette/*.json instead
# Source from bash/zsh. Appends the Lava colors to FZF_DEFAULT_OPTS (idempotent).
LAVA_FZF_COLORS='--color=fg:#CFC6BE,bg:-1,hl:#E86B3F,fg+:#F5EFE8,bg+:#3A2016,hl+:#E86B3F,info:#8A8079,prompt:#E86B3F,pointer:#E86B3F,marker:#E0AA50,spinner:#E0AA50,header:#74BBAC,border:#3A302A,label:#CFC6BE,query:#F5EFE8,gutter:-1,separator:#3A302A,scrollbar:#61564F'
case " $FZF_DEFAULT_OPTS " in
  *" $LAVA_FZF_COLORS "*) ;;
  *) export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }$LAVA_FZF_COLORS" ;;
esac
