# Generated by scripts/build.mjs — do not edit, change palette/*.json instead
# Source from bash/zsh. Appends the Lava colors to FZF_DEFAULT_OPTS (idempotent).
LAVA_FZF_COLORS='--color=fg:#50453f,bg:-1,hl:#d65a31,fg+:#2b211d,bg+:#f3d5bf,hl+:#d65a31,info:#756860,prompt:#d65a31,pointer:#d65a31,marker:#d8a146,spinner:#d8a146,header:#1f7265,border:#ddd1c4,label:#50453f,query:#2b211d,gutter:-1,separator:#ddd1c4,scrollbar:#b9aca1'
case " $FZF_DEFAULT_OPTS " in
  *" $LAVA_FZF_COLORS "*) ;;
  *) export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }$LAVA_FZF_COLORS" ;;
esac
