# Generated by scripts/build.mjs — do not edit, change palette/*.json instead
# Source from bash/zsh. Appends the Lava colors to FZF_DEFAULT_OPTS (idempotent).
LAVA_FZF_COLORS='--color=fg:#56514B,bg:-1,hl:#B74727,fg+:#34312F,bg+:#E3E8ED,hl+:#B74727,info:#736D65,prompt:#B74727,pointer:#B74727,marker:#D8A146,spinner:#D8A146,header:#246E61,border:#C9C4BA,label:#56514B,query:#34312F,gutter:-1,separator:#C9C4BA,scrollbar:#8C857B'
case " $FZF_DEFAULT_OPTS " in
  *" $LAVA_FZF_COLORS "*) ;;
  *) export FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }$LAVA_FZF_COLORS" ;;
esac
