# Generated by scripts/build.mjs — do not edit, change palette/*.json instead
set -g mode-style "fg=#34312F,bg=#E3E8ED"
set -g message-style "fg=#B74727,bg=#EEECE6"
set -g message-command-style "fg=#B74727,bg=#EEECE6"
set -g pane-border-style "fg=#C9C4BA"
set -g pane-active-border-style "fg=#B74727"
set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#56514B,bg=#EEECE6"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left "#[fg=#FAFAFA,bg=#B74727,bold] #S #[fg=#B74727,bg=#EEECE6,nobold]"
set -g status-right "#{prefix_highlight}#[fg=#56514B,bg=#EEECE6] %Y-%m-%d  %H:%M #[fg=#2B211D,bg=#D8A146,bold] #h "
setw -g window-status-activity-style "underscore,fg=#87601C,bg=#EEECE6"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#79736B,bg=#EEECE6"
setw -g window-status-format "#[fg=#79736B,bg=#EEECE6] #I  #W #F "
setw -g window-status-current-format "#[fg=#B74727,bg=#EAE7DF,bold] #I  #W #F "

# Popups (tmux-floax, tmux-sessionx, tmux-fzf, fzf-url…)
set -g popup-style "fg=#34312F,bg=#F8F7F3"
set -g popup-border-style "fg=#B74727"
set -g popup-border-lines "rounded"

# Plugin options — only set when you haven't chosen your own value
%if "#{==:#{@floax-border-color},}"
set -g @floax-border-color "#B74727"
%endif
%if "#{==:#{@floax-text-color},}"
set -g @floax-text-color "#34312F"
%endif
%if "#{==:#{@sessionx-additional-options},}"
set -g @sessionx-additional-options "--color=bg+:#E3E8ED,fg+:#34312F,hl:#B74727,hl+:#B74727,pointer:#B74727,marker:#D8A146,prompt:#B74727,info:#736D65,border:#C9C4BA,spinner:#D8A146,header:#246E61"
%endif
%if "#{==:#{@prefix_highlight_bg},}"
set -g @prefix_highlight_fg "#2B211D"
set -g @prefix_highlight_bg "#D8A146"
%endif
