# Generated by scripts/build.mjs — do not edit, change palette/*.json instead
set -g mode-style "fg=#f5efe8,bg=#3a2016"
set -g message-style "fg=#e86b3f,bg=#181513"
set -g message-command-style "fg=#e86b3f,bg=#181513"
set -g pane-border-style "fg=#3a302a"
set -g pane-active-border-style "fg=#e86b3f"
set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#cfc6be,bg=#181513"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left "#[fg=#fafafa,bg=#e86b3f,bold] #S #[fg=#e86b3f,bg=#181513,nobold]"
set -g status-right "#{prefix_highlight}#[fg=#cfc6be,bg=#181513] %Y-%m-%d  %H:%M #[fg=#2b211d,bg=#e0aa50,bold] #h "
setw -g window-status-activity-style "underscore,fg=#e0aa50,bg=#181513"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#7d716a,bg=#181513"
setw -g window-status-format "#[fg=#7d716a,bg=#181513] #I  #W #F "
setw -g window-status-current-format "#[fg=#e86b3f,bg=#1a1715,bold] #I  #W #F "

# Popups (tmux-floax, tmux-sessionx, tmux-fzf, fzf-url…)
set -g popup-style "fg=#f5efe8,bg=#0f0e0d"
set -g popup-border-style "fg=#e86b3f"
set -g popup-border-lines "rounded"

# Plugin options — only set when you haven't chosen your own value
%if "#{==:#{@floax-border-color},}"
set -g @floax-border-color "#e86b3f"
%endif
%if "#{==:#{@floax-text-color},}"
set -g @floax-text-color "#f5efe8"
%endif
%if "#{==:#{@sessionx-additional-options},}"
set -g @sessionx-additional-options "--color=bg+:#3a2016,fg+:#f5efe8,hl:#e86b3f,hl+:#e86b3f,pointer:#e86b3f,marker:#e0aa50,prompt:#e86b3f,info:#8a8079,border:#3a302a,spinner:#e0aa50,header:#74bbac"
%endif
%if "#{==:#{@prefix_highlight_bg},}"
set -g @prefix_highlight_fg "#2b211d"
set -g @prefix_highlight_bg "#e0aa50"
%endif
