# Generated by scripts/build.mjs — do not edit, change palette/*.json instead
set -g mode-style "fg=#34312f,bg=#e3e8ed"
set -g message-style "fg=#b74727,bg=#eeece6"
set -g message-command-style "fg=#b74727,bg=#eeece6"
set -g pane-border-style "fg=#c9c4ba"
set -g pane-active-border-style "fg=#b74727"
set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#56514b,bg=#eeece6"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left "#[fg=#fafafa,bg=#b74727,bold] #S #[fg=#b74727,bg=#eeece6,nobold]"
set -g status-right "#{prefix_highlight}#[fg=#56514b,bg=#eeece6] %Y-%m-%d  %H:%M #[fg=#2b211d,bg=#d8a146,bold] #h "
setw -g window-status-activity-style "underscore,fg=#87601c,bg=#eeece6"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#79736b,bg=#eeece6"
setw -g window-status-format "#[fg=#79736b,bg=#eeece6] #I  #W #F "
setw -g window-status-current-format "#[fg=#b74727,bg=#eae7df,bold] #I  #W #F "

# Popups (tmux-floax, tmux-sessionx, tmux-fzf, fzf-url…)
set -g popup-style "fg=#34312f,bg=#f8f7f3"
set -g popup-border-style "fg=#b74727"
set -g popup-border-lines "rounded"

# Plugin options — only set when you haven't chosen your own value
%if "#{==:#{@floax-border-color},}"
set -g @floax-border-color "#b74727"
%endif
%if "#{==:#{@floax-text-color},}"
set -g @floax-text-color "#34312f"
%endif
%if "#{==:#{@sessionx-additional-options},}"
set -g @sessionx-additional-options "--color=bg+:#e3e8ed,fg+:#34312f,hl:#b74727,hl+:#b74727,pointer:#b74727,marker:#d8a146,prompt:#b74727,info:#736d65,border:#c9c4ba,spinner:#d8a146,header:#246e61"
%endif
%if "#{==:#{@prefix_highlight_bg},}"
set -g @prefix_highlight_fg "#2b211d"
set -g @prefix_highlight_bg "#d8a146"
%endif
