# Generated by scripts/build.mjs — do not edit, change palette/*.json instead
set -g mode-style "fg=#F5EFE8,bg=#3A2016"
set -g message-style "fg=#E86B3F,bg=#181513"
set -g message-command-style "fg=#E86B3F,bg=#181513"
set -g pane-border-style "fg=#3A302A"
set -g pane-active-border-style "fg=#E86B3F"
set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#CFC6BE,bg=#181513"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left "#[fg=#FAFAFA,bg=#E86B3F,bold] #S #[fg=#E86B3F,bg=#181513,nobold]"
set -g status-right "#{prefix_highlight}#[fg=#CFC6BE,bg=#181513] %Y-%m-%d  %H:%M #[fg=#2B211D,bg=#E0AA50,bold] #h "
setw -g window-status-activity-style "underscore,fg=#E0AA50,bg=#181513"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#7D716A,bg=#181513"
setw -g window-status-format "#[fg=#7D716A,bg=#181513] #I  #W #F "
setw -g window-status-current-format "#[fg=#E86B3F,bg=#1A1715,bold] #I  #W #F "

# Popups (tmux-floax, tmux-sessionx, tmux-fzf, fzf-url…)
set -g popup-style "fg=#F5EFE8,bg=#0F0E0D"
set -g popup-border-style "fg=#E86B3F"
set -g popup-border-lines "rounded"

# Plugin options — only set when you haven't chosen your own value
%if "#{==:#{@floax-border-color},}"
set -g @floax-border-color "#E86B3F"
%endif
%if "#{==:#{@floax-text-color},}"
set -g @floax-text-color "#F5EFE8"
%endif
%if "#{==:#{@sessionx-additional-options},}"
set -g @sessionx-additional-options "--color=bg+:#3A2016,fg+:#F5EFE8,hl:#E86B3F,hl+:#E86B3F,pointer:#E86B3F,marker:#E0AA50,prompt:#E86B3F,info:#8A8079,border:#3A302A,spinner:#E0AA50,header:#74BBAC"
%endif
%if "#{==:#{@prefix_highlight_bg},}"
set -g @prefix_highlight_fg "#2B211D"
set -g @prefix_highlight_bg "#E0AA50"
%endif
