# Generated by scripts/build.mjs — do not edit, change palette/*.json instead
set -g mode-style "fg=#2b211d,bg=#f3d5bf"
set -g message-style "fg=#d65a31,bg=#f5f0e7"
set -g message-command-style "fg=#d65a31,bg=#f5f0e7"
set -g pane-border-style "fg=#ddd1c4"
set -g pane-active-border-style "fg=#d65a31"
set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#50453f,bg=#f5f0e7"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left "#[fg=#fafafa,bg=#d65a31,bold] #S #[fg=#d65a31,bg=#f5f0e7,nobold]"
set -g status-right "#{prefix_highlight}#[fg=#50453f,bg=#f5f0e7] %Y-%m-%d  %H:%M #[fg=#2b211d,bg=#d8a146,bold] #h "
setw -g window-status-activity-style "underscore,fg=#9a6418,bg=#f5f0e7"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#9f9288,bg=#f5f0e7"
setw -g window-status-format "#[fg=#9f9288,bg=#f5f0e7] #I  #W #F "
setw -g window-status-current-format "#[fg=#d65a31,bg=#f4eee5,bold] #I  #W #F "

# Popups (tmux-floax, tmux-sessionx, tmux-fzf, fzf-url…)
set -g popup-style "fg=#2b211d,bg=#faf6ef"
set -g popup-border-style "fg=#d65a31"
set -g popup-border-lines "rounded"

# Plugin options — only set when you haven't chosen your own value
%if "#{==:#{@floax-border-color},}"
set -g @floax-border-color "#d65a31"
%endif
%if "#{==:#{@floax-text-color},}"
set -g @floax-text-color "#2b211d"
%endif
%if "#{==:#{@sessionx-additional-options},}"
set -g @sessionx-additional-options "--color=bg+:#f3d5bf,fg+:#2b211d,hl:#d65a31,hl+:#d65a31,pointer:#d65a31,marker:#d8a146,prompt:#d65a31,info:#756860,border:#ddd1c4,spinner:#d8a146,header:#1f7265"
%endif
%if "#{==:#{@prefix_highlight_bg},}"
set -g @prefix_highlight_fg "#2b211d"
set -g @prefix_highlight_bg "#d8a146"
%endif
