local M = {}

function M.get(c, config)
  local bg = config.transparent and "NONE" or c.bg
  local bg_float = config.transparent and "NONE" or c.bg_float
  local comment_style = { fg = c.comment, italic = config.italic_comments }

  local hl = {
    -- Editor UI
    Normal = { fg = c.fg, bg = bg },
    NormalNC = { fg = c.fg, bg = bg },
    NormalFloat = { fg = c.fg, bg = bg_float },
    FloatBorder = { fg = c.border, bg = bg_float },
    FloatTitle = { fg = c.primary, bg = bg_float, bold = true },
    Cursor = { fg = c.bg, bg = c.fg },
    CursorLine = { bg = c.bg_highlight },
    CursorColumn = { bg = c.bg_highlight },
    CursorLineNr = { fg = c.primary, bold = true },
    LineNr = { fg = c.fg_gutter },
    SignColumn = { fg = c.fg_gutter, bg = bg },
    FoldColumn = { fg = c.fg_gutter, bg = bg },
    Folded = { fg = c.comment, bg = c.bg_highlight },
    ColorColumn = { bg = c.bg_dark },
    WinSeparator = { fg = c.border },
    VertSplit = { fg = c.border },
    StatusLine = { fg = c.fg_dark, bg = c.bg_dark },
    StatusLineNC = { fg = c.dark3, bg = c.bg_dark },
    TabLine = { fg = c.dark3, bg = c.bg_dark },
    TabLineFill = { bg = c.bg_dark },
    TabLineSel = { fg = c.on_primary, bg = c.primary, bold = true },
    WinBar = { fg = c.fg_dark, bg = bg },
    WinBarNC = { fg = c.dark3, bg = bg },
    Visual = { bg = c.bg_visual },
    VisualNOS = { bg = c.bg_visual },
    Search = { fg = c.on_highlight, bg = c.highlight },
    IncSearch = { fg = c.on_primary, bg = c.primary },
    CurSearch = { fg = c.on_primary, bg = c.primary },
    Substitute = { fg = c.on_primary, bg = c.red },
    MatchParen = { fg = c.primary, bold = true, underline = true },
    Pmenu = { fg = c.fg, bg = c.bg_float },
    PmenuSel = { bg = c.bg_visual, bold = true },
    PmenuSbar = { bg = c.bg_highlight },
    PmenuThumb = { bg = c.fg_gutter },
    NonText = { fg = c.fg_gutter },
    Whitespace = { fg = c.border },
    SpecialKey = { fg = c.dark3 },
    EndOfBuffer = { fg = c.bg },
    Directory = { fg = c.blue },
    Title = { fg = c.primary, bold = true },
    Question = { fg = c.teal },
    MoreMsg = { fg = c.teal },
    ModeMsg = { fg = c.fg_dark, bold = true },
    ErrorMsg = { fg = c.error },
    WarningMsg = { fg = c.warning },
    WildMenu = { bg = c.bg_visual },
    QuickFixLine = { bg = c.bg_visual, bold = true },
    SpellBad = { sp = c.error, undercurl = true },
    SpellCap = { sp = c.warning, undercurl = true },
    SpellLocal = { sp = c.info, undercurl = true },
    SpellRare = { sp = c.hint, undercurl = true },

    -- Syntax
    Comment = comment_style,
    Constant = { fg = c.terracotta },
    String = { fg = c.green },
    Character = { fg = c.green },
    Number = { fg = c.terracotta },
    Boolean = { fg = c.terracotta },
    Float = { fg = c.terracotta },
    Identifier = { fg = c.fg },
    Function = { fg = c.blue },
    Statement = { fg = c.orange },
    Conditional = { fg = c.orange },
    Repeat = { fg = c.orange },
    Label = { fg = c.orange },
    Operator = { fg = c.cyan },
    Keyword = { fg = c.orange, italic = true },
    Exception = { fg = c.red },
    PreProc = { fg = c.magenta },
    Include = { fg = c.magenta },
    Define = { fg = c.magenta },
    Macro = { fg = c.magenta },
    Type = { fg = c.yellow },
    StorageClass = { fg = c.yellow },
    Structure = { fg = c.yellow },
    Typedef = { fg = c.yellow },
    Special = { fg = c.teal },
    SpecialChar = { fg = c.teal },
    Tag = { fg = c.red },
    Delimiter = { fg = c.fg_dark },
    Debug = { fg = c.terracotta },
    Underlined = { underline = true },
    Error = { fg = c.error },
    Todo = { fg = c.on_highlight, bg = c.highlight, bold = true },

    -- Treesitter
    ["@variable"] = { fg = c.fg },
    ["@variable.builtin"] = { fg = c.red, italic = true },
    ["@variable.parameter"] = { fg = c.fg_dark, italic = true },
    ["@variable.member"] = { fg = c.cyan },
    ["@property"] = { fg = c.cyan },
    ["@constant"] = { fg = c.terracotta },
    ["@constant.builtin"] = { fg = c.terracotta, italic = true },
    ["@module"] = { fg = c.yellow },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = c.teal },
    ["@string.regexp"] = { fg = c.teal },
    ["@string.special.url"] = { fg = c.blue, underline = true },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = c.blue, italic = true },
    ["@function.call"] = { fg = c.blue },
    ["@function.method"] = { fg = c.blue },
    ["@constructor"] = { fg = c.yellow },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { fg = c.orange, italic = true },
    ["@keyword.return"] = { fg = c.orange, italic = true },
    ["@keyword.import"] = { fg = c.magenta },
    ["@keyword.operator"] = { fg = c.orange },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.delimiter"] = { fg = c.fg_dark },
    ["@punctuation.bracket"] = { fg = c.fg_dark },
    ["@punctuation.special"] = { fg = c.teal },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.yellow, italic = true },
    ["@attribute"] = { fg = c.magenta },
    ["@tag"] = { fg = c.red },
    ["@tag.attribute"] = { fg = c.yellow, italic = true },
    ["@tag.delimiter"] = { fg = c.fg_dark },
    ["@comment"] = { link = "Comment" },
    ["@markup.heading"] = { fg = c.primary, bold = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.teal },
    ["@markup.link.url"] = { fg = c.blue, underline = true },
    ["@markup.raw"] = { fg = c.green },
    ["@markup.list"] = { fg = c.red },

    -- LSP semantic tokens
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.enumMember"] = { link = "@constant" },

    -- Diagnostics
    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warning },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticUnderlineError = { sp = c.error, undercurl = true },
    DiagnosticUnderlineWarn = { sp = c.warning, undercurl = true },
    DiagnosticUnderlineInfo = { sp = c.info, undercurl = true },
    DiagnosticUnderlineHint = { sp = c.hint, undercurl = true },
    DiagnosticVirtualTextError = { fg = c.error, bg = c.bg_highlight },
    DiagnosticVirtualTextWarn = { fg = c.warning, bg = c.bg_highlight },
    DiagnosticVirtualTextInfo = { fg = c.info, bg = c.bg_highlight },
    DiagnosticVirtualTextHint = { fg = c.hint, bg = c.bg_highlight },
    LspReferenceText = { bg = c.bg_highlight },
    LspReferenceRead = { bg = c.bg_highlight },
    LspReferenceWrite = { bg = c.bg_highlight, underline = true },
    LspInlayHint = { fg = c.dark3, bg = c.bg_highlight },

    -- Diff / Git
    DiffAdd = { bg = c.diff_add },
    DiffChange = { bg = c.diff_change },
    DiffDelete = { bg = c.diff_delete },
    DiffText = { bg = c.diff_text },
    Added = { fg = c.git_add },
    Changed = { fg = c.git_change },
    Removed = { fg = c.git_delete },
    GitSignsAdd = { fg = c.git_add },
    GitSignsChange = { fg = c.git_change },
    GitSignsDelete = { fg = c.git_delete },

    -- Telescope
    TelescopeBorder = { fg = c.border, bg = bg_float },
    TelescopeNormal = { fg = c.fg, bg = bg_float },
    TelescopeTitle = { fg = c.primary, bold = true },
    TelescopeSelection = { bg = c.bg_visual },
    TelescopeMatching = { fg = c.primary, bold = true },
    TelescopePromptPrefix = { fg = c.red },

    -- Snacks / mini / which-key / blink
    WhichKey = { fg = c.primary },
    WhichKeyGroup = { fg = c.blue },
    WhichKeyDesc = { fg = c.fg_dark },
    BlinkCmpMenu = { link = "Pmenu" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    BlinkCmpLabelMatch = { fg = c.primary, bold = true },
    BlinkCmpMenuBorder = { link = "FloatBorder" },
    BlinkCmpDocBorder = { link = "FloatBorder" },

    -- neo-tree
    NeoTreeNormal = { fg = c.fg_dark, bg = c.bg_dark },
    NeoTreeNormalNC = { fg = c.fg_dark, bg = c.bg_dark },
    NeoTreeWinSeparator = { fg = c.bg_dark, bg = c.bg_dark },
    NeoTreeRootName = { fg = c.primary, bold = true },
    NeoTreeDirectoryIcon = { fg = c.terracotta },
    NeoTreeDirectoryName = { fg = c.fg_dark },
    NeoTreeFileNameOpened = { fg = c.fg, bold = true },
    NeoTreeIndentMarker = { fg = c.border },
    NeoTreeGitAdded = { fg = c.git_add },
    NeoTreeGitModified = { fg = c.git_change },
    NeoTreeGitDeleted = { fg = c.git_delete },
    NeoTreeGitUntracked = { fg = c.teal },
    NeoTreeGitIgnored = { fg = c.dark3 },
    NeoTreeTabActive = { fg = c.primary, bg = c.bg_dark, bold = true },
    NeoTreeTabInactive = { fg = c.dark3, bg = c.bg_dark },

    -- noice
    NoiceCmdlinePopupBorder = { fg = c.primary },
    NoiceCmdlinePopupTitle = { fg = c.primary },
    NoiceCmdlineIcon = { fg = c.primary },
    NoiceCmdlinePopupBorderSearch = { fg = c.highlight },
    NoiceCmdlineIconSearch = { fg = c.highlight },
    NoiceConfirmBorder = { fg = c.primary },

    -- snacks (dashboard, picker, notifier, lazygit, terminal)
    SnacksDashboardHeader = { fg = c.primary },
    SnacksDashboardKey = { fg = c.highlight },
    SnacksDashboardIcon = { fg = c.terracotta },
    SnacksDashboardDesc = { fg = c.fg_dark },
    SnacksDashboardFooter = { fg = c.comment },
    SnacksPickerMatch = { fg = c.primary, bold = true },
    SnacksPickerBorder = { link = "FloatBorder" },
    SnacksPickerTitle = { fg = c.primary, bold = true },
    SnacksIndent = { fg = c.border },
    SnacksIndentScope = { fg = c.terracotta },
    SnacksNotifierBorderInfo = { fg = c.info },
    SnacksNotifierBorderWarn = { fg = c.warning },
    SnacksNotifierBorderError = { fg = c.error },

    -- trouble
    TroubleNormal = { fg = c.fg_dark, bg = c.bg_dark },
    TroubleNormalNC = { fg = c.fg_dark, bg = c.bg_dark },
    TroubleCount = { fg = c.primary, bg = c.bg_highlight },

    -- todo-comments
    TodoBgTODO = { fg = c.bg, bg = c.blue, bold = true },
    TodoFgTODO = { fg = c.blue },
    TodoBgFIX = { fg = c.on_primary, bg = c.red, bold = true },
    TodoFgFIX = { fg = c.red },
    TodoBgWARN = { fg = c.on_highlight, bg = c.highlight, bold = true },
    TodoFgWARN = { fg = c.highlight },
    TodoBgNOTE = { fg = c.bg, bg = c.teal, bold = true },
    TodoFgNOTE = { fg = c.teal },
    TodoBgHACK = { fg = c.on_primary, bg = c.primary, bold = true },
    TodoFgHACK = { fg = c.primary },
    TodoBgPERF = { fg = c.bg, bg = c.magenta, bold = true },
    TodoFgPERF = { fg = c.magenta },

    -- rainbow-delimiters
    RainbowDelimiterRed = { fg = c.red },
    RainbowDelimiterOrange = { fg = c.orange },
    RainbowDelimiterYellow = { fg = c.yellow },
    RainbowDelimiterGreen = { fg = c.green },
    RainbowDelimiterCyan = { fg = c.cyan },
    RainbowDelimiterBlue = { fg = c.blue },
    RainbowDelimiterViolet = { fg = c.magenta },

    -- nvim-navic / barbecue (barbecue with theme = "auto" reads these)
    NavicText = { fg = c.fg_dark },
    NavicSeparator = { fg = c.dark3 },
    NavicIconsFile = { fg = c.fg_dark },
    NavicIconsModule = { fg = c.yellow },
    NavicIconsNamespace = { fg = c.yellow },
    NavicIconsClass = { fg = c.yellow },
    NavicIconsMethod = { fg = c.blue },
    NavicIconsFunction = { fg = c.blue },
    NavicIconsConstructor = { fg = c.yellow },
    NavicIconsProperty = { fg = c.cyan },
    NavicIconsField = { fg = c.cyan },
    NavicIconsVariable = { fg = c.fg },
    NavicIconsConstant = { fg = c.terracotta },
    NavicIconsInterface = { fg = c.yellow },
    NavicIconsEnum = { fg = c.yellow },
    NavicIconsEnumMember = { fg = c.terracotta },
    NavicIconsStruct = { fg = c.yellow },
    NavicIconsKey = { fg = c.orange },
    NavicIconsString = { fg = c.green },
    NavicIconsNumber = { fg = c.terracotta },
    NavicIconsBoolean = { fg = c.terracotta },
    NavicIconsArray = { fg = c.teal },
    NavicIconsObject = { fg = c.teal },

    -- which-key extras
    WhichKeySeparator = { fg = c.dark3 },
    WhichKeyBorder = { link = "FloatBorder" },

    -- lazy.nvim
    LazyNormal = { fg = c.fg, bg = bg_float },
    LazyH1 = { fg = c.on_primary, bg = c.primary, bold = true },
    LazyH2 = { fg = c.primary, bold = true },
    LazyButton = { fg = c.fg_dark, bg = c.bg_highlight },
    LazyButtonActive = { fg = c.on_primary, bg = c.primary, bold = true },
    LazySpecial = { fg = c.primary },
    LazyProgressDone = { fg = c.primary, bold = true },
    LazyProgressTodo = { fg = c.border },
    LazyProp = { fg = c.fg_dark },
    LazyValue = { fg = c.green },
    LazyDimmed = { fg = c.comment },
    LazyReasonPlugin = { fg = c.red },
    LazyReasonEvent = { fg = c.yellow },
    LazyReasonKeys = { fg = c.teal },
    LazyReasonCmd = { fg = c.terracotta },
    LazyReasonFt = { fg = c.magenta },
    LazyReasonStart = { fg = c.fg },
    LazyReasonSource = { fg = c.cyan },
    LazyReasonImport = { fg = c.fg },
    LazyReasonRuntime = { fg = c.blue },
    LazyCommit = { fg = c.green },
    LazyCommitType = { fg = c.magenta },
    LazyUrl = { fg = c.blue, underline = true },

    -- mason
    MasonNormal = { fg = c.fg, bg = bg_float },
    MasonHeader = { fg = c.on_primary, bg = c.primary, bold = true },
    MasonHeaderSecondary = { fg = c.on_highlight, bg = c.highlight, bold = true },
    MasonHighlight = { fg = c.primary },
    MasonHighlightBlock = { fg = c.on_primary, bg = c.primary },
    MasonHighlightBlockBold = { fg = c.on_primary, bg = c.primary, bold = true },
    MasonHighlightSecondary = { fg = c.highlight },
    MasonHighlightBlockSecondary = { fg = c.on_highlight, bg = c.highlight },
    MasonHighlightBlockBoldSecondary = { fg = c.on_highlight, bg = c.highlight, bold = true },
    MasonHeading = { fg = c.fg, bold = true },
    MasonMuted = { fg = c.comment },
    MasonMutedBlock = { fg = c.fg_dark, bg = c.bg_highlight },
    MasonMutedBlockBold = { fg = c.fg, bg = c.bg_highlight, bold = true },
    MasonError = { fg = c.error },
    MasonWarning = { fg = c.warning },

    -- octo.nvim
    OctoEditable = { bg = c.bg_float },
    OctoBubble = { fg = c.fg, bg = c.bg_highlight },
    OctoUser = { fg = c.primary },
    OctoUserViewer = { fg = c.on_primary, bg = c.primary },
    OctoTimelineItemHeading = { fg = c.comment },
    OctoStateOpen = { fg = c.green, bold = true },
    OctoStateClosed = { fg = c.red, bold = true },
    OctoStateMerged = { fg = c.magenta, bold = true },
    OctoStatePending = { fg = c.yellow, bold = true },
    OctoStateDraft = { fg = c.comment, bold = true },
    OctoPullAdditions = { fg = c.git_add },
    OctoPullDeletions = { fg = c.git_delete },
    OctoPullModifications = { fg = c.git_change },

    -- copilot / ghost text
    CopilotSuggestion = { fg = c.comment, italic = true },
    CopilotAnnotation = { fg = c.comment, italic = true },
    BlinkCmpGhostText = { fg = c.comment, italic = true },

    -- yanky
    YankyPut = { fg = c.on_highlight, bg = c.highlight },
    YankyYanked = { fg = c.on_primary, bg = c.primary },
  }

  return hl
end

return M
