#!/usr/bin/env node
// Generates every port of the theme from palette/<name>.json.
// Usage: node scripts/build.mjs   (no dependencies)

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { derive } from "./derive.mjs";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const HEADER = "Generated by scripts/build.mjs — do not edit, change palette/*.json instead";

const out = (path, content) => {
  const full = join(root, path);
  mkdirSync(dirname(full), { recursive: true });
  writeFileSync(full, content);
  console.log(`  ${path}`);
};

// ---------------------------------------------------------------- targets

const targets = {
  nvim: (p) => {
    const lua = (obj, indent = "  ") =>
      Object.entries(obj)
        .map(([k, v]) => `${indent}${k} = "${v}",`)
        .join("\n");
    return [
      `lua/${p.family}/palettes/${p.variant}.lua`,
      `-- ${HEADER}\nreturn {\n${lua(p.colors)}\n  terminal = {\n${lua(p.terminal, "    ")}\n  },\n}\n`,
    ];
  },

  wezterm: ({ name, displayName, colors: c, terminal: t }) => [
    `extras/wezterm/${name}.toml`,
    `# ${HEADER}
[colors]
foreground = "${c.fg}"
background = "${c.bg}"
cursor_bg = "${c.fg}"
cursor_fg = "${c.bg}"
cursor_border = "${c.fg}"
selection_bg = "${c.bg_visual}"
selection_fg = "${c.fg}"
split = "${c.border}"
compose_cursor = "${c.primary}"
scrollbar_thumb = "${c.fg_gutter}"
ansi = ["${t.black}", "${t.red}", "${t.green}", "${t.yellow}", "${t.blue}", "${t.magenta}", "${t.cyan}", "${t.white}"]
brights = ["${t.bright_black}", "${t.bright_red}", "${t.bright_green}", "${t.bright_yellow}", "${t.bright_blue}", "${t.bright_magenta}", "${t.bright_cyan}", "${t.bright_white}"]

[colors.tab_bar]
background = "${c.bg_dark}"
inactive_tab_edge = "${c.border}"

[colors.tab_bar.active_tab]
bg_color = "${c.primary}"
fg_color = "${c.on_primary}"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
bg_color = "${c.bg_dark}"
fg_color = "${c.dark3}"

[colors.tab_bar.inactive_tab_hover]
bg_color = "${c.bg_highlight}"
fg_color = "${c.fg_dark}"

[colors.tab_bar.new_tab]
bg_color = "${c.bg_dark}"
fg_color = "${c.dark3}"

[colors.tab_bar.new_tab_hover]
bg_color = "${c.bg_highlight}"
fg_color = "${c.fg}"

[metadata]
name = "${displayName}"
author = "Pompei Tech"
`,
  ],

  tmux: ({ name, colors: c }) => [
    `extras/tmux/${name}.tmux`,
    `# ${HEADER}
set -g mode-style "fg=${c.fg},bg=${c.bg_visual}"
set -g message-style "fg=${c.primary},bg=${c.bg_dark}"
set -g message-command-style "fg=${c.primary},bg=${c.bg_dark}"
set -g pane-border-style "fg=${c.border}"
set -g pane-active-border-style "fg=${c.primary}"
set -g status "on"
set -g status-justify "left"
set -g status-style "fg=${c.fg_dark},bg=${c.bg_dark}"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left "#[fg=${c.on_primary},bg=${c.primary},bold] #S #[fg=${c.primary},bg=${c.bg_dark},nobold]"
set -g status-right "#{prefix_highlight}#[fg=${c.fg_dark},bg=${c.bg_dark}] %Y-%m-%d  %H:%M #[fg=${c.on_highlight},bg=${c.highlight},bold] #h "
setw -g window-status-activity-style "underscore,fg=${c.yellow},bg=${c.bg_dark}"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=${c.dark3},bg=${c.bg_dark}"
setw -g window-status-format "#[fg=${c.dark3},bg=${c.bg_dark}] #I  #W #F "
setw -g window-status-current-format "#[fg=${c.primary},bg=${c.bg_highlight},bold] #I  #W #F "

# Popups (tmux-floax, tmux-sessionx, tmux-fzf, fzf-url…)
set -g popup-style "fg=${c.fg},bg=${c.bg}"
set -g popup-border-style "fg=${c.primary}"
set -g popup-border-lines "rounded"

# Plugin options — only set when you haven't chosen your own value
%if "#{==:#{@floax-border-color},}"
set -g @floax-border-color "${c.primary}"
%endif
%if "#{==:#{@floax-text-color},}"
set -g @floax-text-color "${c.fg}"
%endif
%if "#{==:#{@sessionx-additional-options},}"
set -g @sessionx-additional-options "--color=bg+:${c.bg_visual},fg+:${c.fg},hl:${c.primary},hl+:${c.primary},pointer:${c.primary},marker:${c.highlight},prompt:${c.primary},info:${c.comment},border:${c.border},spinner:${c.highlight},header:${c.teal}"
%endif
%if "#{==:#{@prefix_highlight_bg},}"
set -g @prefix_highlight_fg "${c.on_highlight}"
set -g @prefix_highlight_bg "${c.highlight}"
%endif
`,
  ],

  kitty: ({ name, colors: c, terminal: t }) => [
    `extras/kitty/${name}.conf`,
    `# ${HEADER}
foreground ${c.fg}
background ${c.bg}
selection_foreground ${c.fg}
selection_background ${c.bg_visual}
cursor ${c.fg}
cursor_text_color ${c.bg}
url_color ${c.blue}
active_border_color ${c.primary}
inactive_border_color ${c.border}
active_tab_foreground ${c.on_primary}
active_tab_background ${c.primary}
inactive_tab_foreground ${c.dark3}
inactive_tab_background ${c.bg_dark}
tab_bar_background ${c.bg_dark}
${ansi(t).map((col, i) => `color${i} ${col}`).join("\n")}
`,
  ],

  ghostty: ({ name, colors: c, terminal: t }) => [
    `extras/ghostty/${name}`,
    `# ${HEADER}
background = ${c.bg}
foreground = ${c.fg}
cursor-color = ${c.fg}
cursor-text = ${c.bg}
selection-background = ${c.bg_visual}
selection-foreground = ${c.fg}
${ansi(t).map((col, i) => `palette = ${i}=${col}`).join("\n")}
`,
  ],

  alacritty: ({ name, colors: c, terminal: t }) => [
    `extras/alacritty/${name}.toml`,
    `# ${HEADER}
[colors.primary]
background = "${c.bg}"
foreground = "${c.fg}"

[colors.cursor]
cursor = "${c.fg}"
text = "${c.bg}"

[colors.selection]
background = "${c.bg_visual}"
text = "${c.fg}"

[colors.normal]
${["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"].map((k) => `${k} = "${t[k]}"`).join("\n")}

[colors.bright]
${["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"].map((k) => `${k} = "${t["bright_" + k]}"`).join("\n")}
`,
  ],

  lazygit: ({ name, colors: c }) => [
    `extras/lazygit/${name}.yml`,
    `# ${HEADER}
gui:
  theme:
    activeBorderColor:
      - "${c.primary}"
      - bold
    inactiveBorderColor:
      - "${c.border}"
    searchingActiveBorderColor:
      - "${c.highlight}"
      - bold
    optionsTextColor:
      - "${c.blue}"
    selectedLineBgColor:
      - "${c.bg_visual}"
    inactiveViewSelectedLineBgColor:
      - "${c.bg_highlight}"
    cherryPickedCommitFgColor:
      - "${c.primary}"
    cherryPickedCommitBgColor:
      - "${c.bg_highlight}"
    markedBaseCommitFgColor:
      - "${c.highlight}"
    markedBaseCommitBgColor:
      - "${c.bg_highlight}"
    unstagedChangesColor:
      - "${c.red}"
    defaultFgColor:
      - "${c.fg}"
  authorColors:
    "*": "${c.terracotta}"
`,
  ],

  iterm: ({ name, colors: c, terminal: t }) => {
    const entry = (key, hex) => {
      const [r, g, b] = [1, 3, 5].map((i) => (parseInt(hex.slice(i, i + 2), 16) / 255).toFixed(6));
      return `\t<key>${key}</key>
\t<dict>
\t\t<key>Alpha Component</key>
\t\t<real>1</real>
\t\t<key>Blue Component</key>
\t\t<real>${b}</real>
\t\t<key>Color Space</key>
\t\t<string>sRGB</string>
\t\t<key>Green Component</key>
\t\t<real>${g}</real>
\t\t<key>Red Component</key>
\t\t<real>${r}</real>
\t</dict>`;
    };
    const entries = [
      ...ansi(t).map((col, i) => [`Ansi ${i} Color`, col]),
      ["Background Color", c.bg],
      ["Foreground Color", c.fg],
      ["Bold Color", c.fg],
      ["Cursor Color", c.fg],
      ["Cursor Text Color", c.bg],
      ["Cursor Guide Color", c.bg_highlight],
      ["Selection Color", c.bg_visual],
      ["Selected Text Color", c.fg],
      ["Link Color", c.blue],
      ["Badge Color", c.primary],
      ["Tab Color", c.bg_dark],
    ];
    return [
      `extras/iterm/${name}.itermcolors`,
      `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${HEADER} -->
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
${entries.map(([k, v]) => entry(k, v)).join("\n")}
</dict>
</plist>
`,
    ];
  },

  fzf: ({ name, colors: c }) => {
    const colors = {
      fg: c.fg_dark, bg: "-1", hl: c.primary,
      "fg+": c.fg, "bg+": c.bg_visual, "hl+": c.primary,
      info: c.comment, prompt: c.primary, pointer: c.primary, marker: c.highlight,
      spinner: c.highlight, header: c.teal, border: c.border, label: c.fg_dark,
      query: c.fg, gutter: "-1", separator: c.border, scrollbar: c.fg_gutter,
    };
    const opts = "--color=" + Object.entries(colors).map(([k, v]) => `${k}:${v}`).join(",");
    return [
      `extras/fzf/${name}.sh`,
      `# ${HEADER}
# Source from bash/zsh. Appends the Lava colors to FZF_DEFAULT_OPTS (idempotent).
LAVA_FZF_COLORS='${opts}'
case " $FZF_DEFAULT_OPTS " in
  *" $LAVA_FZF_COLORS "*) ;;
  *) export FZF_DEFAULT_OPTS="\${FZF_DEFAULT_OPTS:+$FZF_DEFAULT_OPTS }$LAVA_FZF_COLORS" ;;
esac
`,
    ];
  },

  p10k: ({ name, colors: c }) => {
    const fg = {
      OS_ICON: c.primary,
      DIR: c.blue,
      DIR_ANCHOR: c.blue,
      DIR_SHORTENED: c.comment,
      STATUS_OK: c.green,
      STATUS_ERROR: c.red,
      STATUS_ERROR_SIGNAL: c.red,
      STATUS_ERROR_PIPE: c.red,
      COMMAND_EXECUTION_TIME: c.yellow,
      BACKGROUND_JOBS: c.teal,
      DIRENV: c.yellow,
      TIME: c.comment,
      CONTEXT: c.comment,
      CONTEXT_ROOT: c.red,
      CONTEXT_REMOTE: c.terracotta,
      VIRTUALENV: c.teal,
      PYENV: c.teal,
      NODE_VERSION: c.green,
      NODENV: c.green,
      NVM: c.green,
      RBENV: c.red,
      GO_VERSION: c.cyan,
      GOENV: c.cyan,
      RUST_VERSION: c.terracotta,
      JAVA_VERSION: c.terracotta,
      KUBECONTEXT_DEFAULT: c.magenta,
      AWS_DEFAULT: c.terracotta,
      GCLOUD: c.blue,
      VIM_SHELL: c.green,
      TODO: c.blue,
    };
    for (const mode of ["VIINS", "VICMD", "VIVIS", "VIOWR"]) {
      fg[`PROMPT_CHAR_OK_${mode}`] = c.primary;
      fg[`PROMPT_CHAR_ERROR_${mode}`] = c.red;
    }
    return [
      `extras/p10k/${name}.zsh`,
      `# ${HEADER}
# Source after ~/.p10k.zsh. Works best with the lean/pure styles (transparent background).
${Object.entries(fg).map(([k, v]) => `typeset -g POWERLEVEL9K_${k}_FOREGROUND='${v}'`).join("\n")}

# Git colors, read by my_git_formatter in ~/.p10k.zsh when it uses \${LAVA_GIT_*:-default}
typeset -g LAVA_GIT_CLEAN='%F{${c.green}}'
typeset -g LAVA_GIT_MODIFIED='%F{${c.yellow}}'
typeset -g LAVA_GIT_UNTRACKED='%F{${c.blue}}'
typeset -g LAVA_GIT_CONFLICTED='%F{${c.red}}'

(( ! $+functions[p10k] )) || p10k reload
`,
    ];
  },

  vscode: (p) => [`vscode/themes/${p.name}-color-theme.json`, JSON.stringify(vscodeTheme(p), null, 2) + "\n"],
};

function ansi(t) {
  const names = ["black", "red", "green", "yellow", "blue", "magenta", "cyan", "white"];
  return [...names.map((n) => t[n]), ...names.map((n) => t["bright_" + n])];
}

function vscodeTheme({ displayName, appearance, colors: c, terminal: t }) {
  const term = Object.fromEntries(
    Object.entries(t).map(([k, v]) => [
      "terminal.ansi" + k.split("_").map((s) => s[0].toUpperCase() + s.slice(1)).join(""),
      v,
    ]),
  );
  const tok = (scope, foreground, fontStyle) => ({ scope, settings: { foreground, ...(fontStyle && { fontStyle }) } });

  return {
    $schema: "vscode://schemas/color-theme",
    name: displayName,
    type: appearance,
    semanticHighlighting: true,
    colors: {
      focusBorder: c.primary + "80",
      foreground: c.fg,
      "widget.shadow": "#00000066",
      "selection.background": c.bg_visual,
      "editor.background": c.bg,
      "editor.foreground": c.fg,
      "editor.lineHighlightBackground": c.bg_highlight,
      "editor.selectionBackground": c.bg_visual,
      "editor.findMatchBackground": c.primary + "66",
      "editor.findMatchHighlightBackground": c.yellow + "33",
      "editor.wordHighlightBackground": c.bg_highlight,
      "editorCursor.foreground": c.fg,
      "editorLineNumber.foreground": c.fg_gutter,
      "editorLineNumber.activeForeground": c.primary,
      "editorIndentGuide.background1": c.border,
      "editorIndentGuide.activeBackground1": c.fg_gutter,
      "editorWhitespace.foreground": c.border,
      "editorBracketMatch.border": c.primary,
      "editorBracketMatch.background": c.bg_highlight,
      "editorError.foreground": c.error,
      "editorWarning.foreground": c.warning,
      "editorInfo.foreground": c.info,
      "editorHint.foreground": c.hint,
      "editorGutter.addedBackground": c.git_add,
      "editorGutter.modifiedBackground": c.git_change,
      "editorGutter.deletedBackground": c.git_delete,
      "editorWidget.background": c.bg_float,
      "editorWidget.border": c.border,
      "editorSuggestWidget.background": c.bg_float,
      "editorSuggestWidget.selectedBackground": c.bg_visual,
      "editorSuggestWidget.highlightForeground": c.primary,
      "editorHoverWidget.background": c.bg_float,
      "editorHoverWidget.border": c.border,
      "editorGroupHeader.tabsBackground": c.bg_dark,
      "editorGroup.border": c.border,
      "tab.activeBackground": c.bg,
      "tab.activeForeground": c.fg,
      "tab.activeBorderTop": c.primary,
      "tab.inactiveBackground": c.bg_dark,
      "tab.inactiveForeground": c.dark3,
      "tab.border": c.bg_dark,
      "activityBar.background": c.bg_dark,
      "activityBar.foreground": c.fg_dark,
      "activityBar.inactiveForeground": c.dark3,
      "activityBar.activeBorder": c.primary,
      "activityBarBadge.background": c.primary,
      "activityBarBadge.foreground": c.on_primary,
      "sideBar.background": c.bg_dark,
      "sideBar.foreground": c.fg_dark,
      "sideBar.border": c.border,
      "sideBarSectionHeader.background": c.bg_dark,
      "sideBarTitle.foreground": c.fg_dark,
      "list.activeSelectionBackground": c.bg_visual,
      "list.activeSelectionForeground": c.fg,
      "list.inactiveSelectionBackground": c.bg_highlight,
      "list.hoverBackground": c.bg_highlight,
      "list.highlightForeground": c.primary,
      "statusBar.background": c.bg_dark,
      "statusBar.foreground": c.fg_dark,
      "statusBar.border": c.border,
      "statusBar.debuggingBackground": c.red,
      "statusBar.debuggingForeground": c.on_primary,
      "statusBarItem.remoteBackground": c.primary,
      "statusBarItem.remoteForeground": c.on_primary,
      "titleBar.activeBackground": c.bg_dark,
      "titleBar.activeForeground": c.fg_dark,
      "titleBar.inactiveBackground": c.bg_dark,
      "titleBar.inactiveForeground": c.dark3,
      "panel.background": c.bg_dark,
      "panel.border": c.border,
      "panelTitle.activeBorder": c.primary,
      "panelTitle.activeForeground": c.fg,
      "panelTitle.inactiveForeground": c.dark3,
      "input.background": c.bg,
      "input.border": c.border,
      "input.placeholderForeground": c.dark3,
      "button.background": c.primary,
      "button.foreground": c.on_primary,
      "button.hoverBackground": c.red,
      "badge.background": c.primary,
      "badge.foreground": c.on_primary,
      "scrollbarSlider.background": c.fg_gutter + "66",
      "scrollbarSlider.hoverBackground": c.fg_gutter + "99",
      "scrollbarSlider.activeBackground": c.fg_gutter,
      "gitDecoration.addedResourceForeground": c.git_add,
      "gitDecoration.modifiedResourceForeground": c.git_change,
      "gitDecoration.deletedResourceForeground": c.git_delete,
      "gitDecoration.untrackedResourceForeground": c.teal,
      "gitDecoration.ignoredResourceForeground": c.dark3,
      "terminal.background": c.bg,
      "terminal.foreground": c.fg,
      "terminalCursor.foreground": c.fg,
      ...term,
    },
    tokenColors: [
      tok(["comment", "punctuation.definition.comment"], c.comment, "italic"),
      tok(["string", "string.quoted", "string.template"], c.green),
      tok(["constant.character.escape", "string.regexp"], c.teal),
      tok(["constant.numeric", "constant.language", "constant.other", "support.constant"], c.terracotta),
      tok(["variable", "variable.other.readwrite"], c.fg),
      tok(["variable.language", "variable.language.this", "variable.language.self"], c.red, "italic"),
      tok(["variable.parameter"], c.fg_dark, "italic"),
      tok(["variable.other.property", "variable.other.object.property", "support.variable.property", "meta.object-literal.key"], c.cyan),
      tok(["keyword", "storage.type", "storage.modifier"], c.orange, "italic"),
      tok(["keyword.control.import", "keyword.control.export", "keyword.control.from", "meta.preprocessor"], c.magenta),
      tok(["keyword.operator", "punctuation.accessor"], c.cyan),
      tok(["entity.name.function", "support.function", "meta.function-call"], c.blue),
      tok(["entity.name.type", "entity.name.class", "support.type", "support.class", "entity.other.inherited-class"], c.yellow),
      tok(["entity.name.namespace", "entity.name.module"], c.yellow),
      tok(["entity.name.tag"], c.red),
      tok(["entity.other.attribute-name"], c.yellow, "italic"),
      tok(["meta.decorator", "entity.name.function.decorator"], c.magenta),
      tok(["punctuation", "meta.brace"], c.fg_dark),
      tok(["markup.heading", "entity.name.section"], c.orange, "bold"),
      tok(["markup.bold"], undefined, "bold"),
      tok(["markup.italic"], undefined, "italic"),
      tok(["markup.underline.link", "string.other.link"], c.blue),
      tok(["markup.inline.raw", "markup.fenced_code"], c.green),
      tok(["markup.inserted"], c.git_add),
      tok(["markup.changed"], c.git_change),
      tok(["markup.deleted"], c.git_delete),
      tok(["invalid"], c.error),
    ].map((t) => (t.settings.foreground === undefined && delete t.settings.foreground, t)),
    semanticTokenColors: {
      parameter: { foreground: c.fg_dark, italic: true },
      property: c.cyan,
      enumMember: c.terracotta,
      namespace: c.yellow,
      "variable.defaultLibrary": c.red,
      "function.defaultLibrary": { foreground: c.blue, italic: true },
      "type.defaultLibrary": { foreground: c.yellow, italic: true },
    },
  };
}

// ---------------------------------------------------------------- main

const palettes = readdirSync(join(root, "palette")).filter((f) => f.endsWith(".json"));
for (const file of palettes) {
  const spec = JSON.parse(readFileSync(join(root, "palette", file), "utf8"));
  for (const [variant, raw] of Object.entries(spec.variants)) {
    const palette = {
      family: spec.name,
      variant,
      name: `${spec.name}-${variant}`,
      displayName: `${spec.displayName} ${variant[0].toUpperCase()}${variant.slice(1)}`,
      appearance: variant,
      ...derive(variant, raw),
    };
    console.log(`${palette.displayName}:`);
    for (const build of Object.values(targets)) out(...build(palette));
  }
}
